name: han4you
description: Een moderne versie van de han4you app!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.5.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  http: ^0.12.2
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7
  webview_cookie_manager: ^1.0.5
  flutter_week_view: ^1.0.0+2
  table_calendar: ^2.3.2
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
